build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    coverage:
      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
            coverage:
              file: build/logs/clover.xml
              format: clover

  environment:
    php: 7.3.0
    variables:
      WP_TESTS_DB_NAME: 'wp_phpunit_tests'
      WP_TESTS_DB_USER: 'root'
      WP_TESTS_DB_PASS: ''
      WP_TESTS_DB_HOST: '127.0.0.1'

  services:
    mysql: 5.7

  dependencies:
    override:
      - composer install --ignore-platform-reqs --no-interaction

  project_setup:
    before:
      - mysql -e "CREATE DATABASE wp_phpunit_tests"

checks:
  php:
    coding_standard:
      name: WordPress
    code_rating: true
    duplication: true

build_failure_conditions:
  - 'issues.label("bug").exists'

coding_style:
    php:
        indentation:
            general:
                use_tabs: true
        spaces:
            around_operators:
                unary_additive: true
                concatenation: true
                negation: true
            within:
                brackets: false
                array_initializer: true
                grouping: true
                function_call: true
                function_declaration: true
                if: true
                for: true
                while: true
                switch: true
                catch: true
                type_cast: false
