name: CI

on: [ push, pull_request ]

jobs:
  phplint:
    uses: pronamic/actions/.github/workflows/phplint.yml@main

  phpcs:
    uses: pronamic/actions/.github/workflows/phpcs.yml@main

  phpstan:
    uses: pronamic/actions/.github/workflows/phpstan.yml@main

  psalm:
    uses: pronamic/actions/.github/workflows/psalm.yml@main

  phpunit:
    uses: pronamic/actions/.github/workflows/phpunit.yml@main

  coverage:
    uses: pronamic/actions/.github/workflows/coverage.yml@main
